### ISSUE TITLE
Running only on $(document).ready(function () {})

### ISSUE THREAD

**Issue by joaobarcia** [louisameline/tooltipster-selectableText#1]
Thank you for your plugin, it was extremely helpful in my case! However the jquery was being called before the DOM had been loaded, so it wasn't working.

Putting your script inside of a $(document).ready(function () {}) made it work for me.

Cheers

**Comment by louisameline** [comment]
Hi and thank you for the kind words :)
Right, waiting for the DOM to be ready is standard procedure when you want to manipulate it but I should probably add a note when I have a minute. Thank you!
